[advisories]
ignore = [
    "RUSTSEC-2024-0370", # `proc-macro-error` is unmaintained (used by `structopt` used by rpc)
    "RUSTSEC-2024-0436", # `paste` is unmaintained (used by `flex-error`)
]
informational_warnings = ["unmaintained"]
severity_threshold = "low"

[output]
deny = ["unmaintained"] # exit on error if unmaintained dependencies are found
format = "terminal"
quiet = false
show_tree = true
